GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
ENCRYPTED_GROQ_API_KEY = "gAAAAABoqo8SeXAnSa_CytG3efkxIWvtick4FDu7kw8eDJCPpJwKIici2SCcueGoIt_CllvwSeDnlZwJr4jJyKQQHUtJPQ90aRoYl5lzlOWNeo8_zDSuP4P9kCTd3ovbfps-uLUhOtkXH3J5-LC4pvKpHjJm19xdxg=="  
OPEN_FOOD_FACTS_API_URL = "https://world.openfoodfacts.org/api/v2"